/**
 * Historial de versiones / novedades de la app.
 * Se muestra en el modal de novedades cuando hay una actualización disponible.
 */

export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  items: string[];
}

// Actualizado: 24/07/2026 — v1.27.0 Chatwoot, MercadoPago Billing y Onboarding
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.27.0',
    date: '24/07/2026',
    title: 'Chatwoot, MercadoPago Billing y Onboarding',
    items: [
      'Chatwoot + Evolution API: sistema de mensajería alternativo a Twilio con webhooks, colas y contacto automático',
      'lib/whatsapp.ts: enrutamiento centralizado entre Twilio y Chatwoot según variable CANAL_MENSAJERIA',
      'API de soporte: canal de feedback para pacientes con envío a Chatwoot o WhatsApp del doctor',
      'Feature toggle "soporte" en sidebar con página de feedback y formulario de contacto',
      'MercadoPago: idempotencia en webhook con caché en memoria TTL 5 min (evita cargos duplicados)',
      'MercadoPago: grace period de 7 días con estado "past_due" antes de cancelar suscripción',
      'Endpoint interno POST /api/internal/suscripciones-vencidas para cron nocturno de downgrade',
      'Onboarding: auto-redirect a /dashboard/onboarding tras registro express (antes iba a suscripción)',
      'Onboarding: nuevo paso "configura WhatsApp" con detección automática de credenciales',
      'WF-01 expandido a 31 nodos: sub-agente clínico para recetas y consultas clínicas con handoff conversacional',
      'ADR-0006 actualizado: arquitectura multi-agente completa (Triaje, Agenda, Clínico)',
      'Soporte: FeatureId, sidebar LifeBuoy, página con formulario de feedback',
    ],
  },
  {
    version: '1.26.0',
    date: '23/07/2026',
    title: 'RLS Multi-Tenant, Backup Fix y Documentación',
    items: [
      'RLS (Row Level Security) habilitado en 10 tablas adicionales: portal_config, web_vitals_metrics, derivaciones, webhook_configs, ordenes_estudio, documentos_medicos, paquetes_portal, consentimiento_compartir, blacklist, consentimientos',
      'Server Components now call withTenantScope(): aislamiento multi-tenant en página de detalle de paciente y onboarding',
      'Migración 0051 con políticas FOR ALL para tablas faltantes',
      'Documentación de Disaster Recovery actualizada con procedimientos de backup y restauración',
      'PgBouncer config ready en código (db.ts), documentado para deploy',
      'Corrección de referencia legal: Ley 26.529 → Ley 20.584 + Ley 19.628',
    ],
  },
  {
    version: '1.25.0',
    date: '22/07/2026',
    title: 'Previsión FONASA, Webhooks Salientes y Derivaciones Cross-Tenant',
    items: [
      'Previsión del paciente: selector de tipo (FONASA/ISAPRE/Particular/PRAIS), tramos A/B/C/D con copagos de referencia, lista completa de ISAPREs chilenas',
      'Badge de previsión en ficha del paciente con tramo FONASA o nombre de ISAPRE',
      'Webhooks salientes configurables: creá webhooks propios por evento (turnos y pacientes) con firma HMAC-SHA256',
      'Delivery automático con 3 reintentos y backoff exponencial, logs de entrega visibles en dashboard',
      'Delivery logs: historial de entregas con status code, respuesta, duración e intentos',
      'UI de integraciones en Configuración con test, regeneración de secret y toggle activo/inactivo',
      'Derivaciones cross-tenant entre organizaciones con consentimiento del paciente',
      'Consentimiento de compartir datos: alcance granular (historial, recetas, turnos, diagnósticos), expiración configurable, revocable',
      'Convenios de intercambio entre tenants para administrar derivaciones inter-organización',
      'Feature gate "integraciones" movido a Professional (antes Premium)',
      'Nuevos features: consentimiento-compartir (Professional), convenios-intercambio (Enterprise)',
    ],
  },
  {
    version: '1.24.0',
    date: '22/07/2026',
    title: 'OCR Especializado, FHIR-lite y Correcciones de Cache',
    items: [
      'OCR especializado por tipo: prompts dedicados para laboratorio (valores, rangos, flags) y recetas (medicamento, dosis, frecuencia)',
      'Confirmación en 3 etapas: paciente sube → OCR extrae → paciente confirma → médico aprueba (inserta en historial clínico)',
      'Manejo de falla: OCR con baja confianza marca el documento para revisión manual del médico',
      'Interfaz de revisión médica: botones Aprobar/Rechazar/Editar con motivo de rechazo inline',
      'Portal: selector de tipo de documento, subida en 2 pasos (upload file → crear doc), diseño por estado',
      'Exportación FHIR-lite: Bundle FHIR R4 con Patient, Encounter, Condition, MedicationRequest',
      'Endpoint GET /api/exportar-fhir/[pacienteId] con verificación de consentimiento y headers FHIR',
      'Feature gate "fhir-export" disponible en plan Professional+',
      'Fix: cache de turnos no se invalidaba correctamente al cambiar estado (wildcard faltante)',
      'Fix: cache de pacientes y médicos con wildcard para invalidación correcta',
      'Fix: bulk-status ahora invalida cache (Next.js + Redis)',
      'Planes actualizados con nuevas funcionalidades en descripciones',
    ],
  },
  {
    version: '1.23.0',
    date: '21/07/2026',
    title: 'Documentos Médicos con OCR por IA',
    items: [
      'Subida de documentos desde el Portal del Paciente (fotos o PDF)',
      'OCR automático con Ollama llava: extrae datos estructurados de imágenes',
      'Confirmación en 2 etapas: paciente confirma → médico aprueba',
      'Integración con historial clínico al aprobar',
      'Dashboard: tab de documentos en ficha del paciente para revisión médica',
      'ADR-0008: Documentos Médicos + OCR con IA',
      'Feature gate "documentos-ocr" disponible en plan Starter+',
    ],
  },
  {
    version: '1.22.0',
    date: '21/07/2026',
    title: 'Transcripción Automática y SOAP por IA',
    items: [
      'Whisper.cpp integrado: transcripción automática de videoconsultas',
      'Pipeline post-consulta: audio → Whisper → Ollama Gemma3 → nota SOAP estructurada',
      'Consentimiento de grabación en el portal del paciente antes de entrar a la sala',
      'Panel de revisión de notas SOAP generadas por IA (aprobar/rechazar/editar)',
      'Política de retención: audio eliminado post-aprobación/rechazo, timeout 48h',
      'Config IA: transcripcionHabilitada y retencionAudioHoras por tenant',
      'Feature gate "transcripcion-soap" disponible en plan Starter+',
      'ADR-0007: Transcripción automática + SOAP por IA',
    ],
  },
  {
    version: '1.21.0',
    date: '21/07/2026',
    title: 'Proxy y Sistema Multi-Agente',
    items: [
      'Migración middleware.ts → proxy.ts (Next.js 16.2+): función exportada renombrada, 0 errores',
      'WF-01 refactorizado: monolítico 17 nodos → 23 nodos multi-agente con handoff conversacional',
      'Triaje Agent + Agenda Agent con memoria compartida vía Postgres Chat Memory',
      'ADR-0006: Multi-agente especializado con handoff (reemplaza ADR-0001)',
      'Backup del workflow original en n8n-workflows/archive/',
    ],
  },
  {
    version: '1.20.0',
    date: '20/07/2026',
    title: 'Doc Completa, Compliance y Metabase',
    items: [
      'Documentación completa: AGENTS.md, ACCESS.md y docs-site (8 archivos mkdocs) actualizados',
      'Metabase agregado: Stack, Roadmap, Infra, instalación, DNS pendiente',
      'Dashboard Compliance: página completa con tabs Auditoría + ARCO + Metabase',
      'WF-12 Scoring No-Show nocturno y WF-03 recordatorios 48h para pacientes de alto riesgo',
      'Tabla consentimiento_log y auditoria_accesos documentadas en base-de-datos.md',
      '6 nuevos endpoints en API Reference: compliance, auditoria-accesos, arco, scores',
      'MkDocs build 0 errores (strict mode)',
    ],
  },
  {
    version: '1.19.0',
    date: '19/07/2026',
    title: 'Scoring No-Show y Dashboard Compliance',
    items: [
      'Migration 0047: riesgo de inasistencia en turnos (risk_score, risk_nivel)',
      'RiskBadge visual en tabla de turnos con score de color (verde/amarillo/naranja/rojo)',
      'WF-12: workflow nocturno para actualizar risk_score y enviar recordatorios 48h',
      'WF-03 modificado: nuevo bloque de recordatorios 48h para pacientes de alto riesgo',
      'Backfill script para calcular scoring histórico de turnos (npm run backfill-scores)',
      'Dashboard Compliance: monitoreo Ley 21.719 con 4 KPIs y 2 charts dinámicos',
      'ComposedChart de tiempo de espera promedio y % de cumplimiento mensual',
      'BarChart horizontal de cumplimiento por médico con colores semáforo',
      'Feature gate "compliance" disponible en plan Professional+',
    ],
  },
  {
    version: '1.18.0',
    date: '13/07/2026',
    title: 'Actualización de estabilidad y UI',
    items: [
      'Novedades renovado: panel con auto-refresh, diseño mejorado, tipos de cambio visibles',
      'Versiones corregidas: bump a v1.18.0 con todo el historial de cambios reflejado',
      'Header badge de novedades corregido: icono coherente, dot preciso, auto-refresh al abrir modal',
      'Página de novedades con datos directos de DB (sin self-fetch)',
      'Timeline visual con badges por tipo (feature, fix, security, refactor)',
      'Transiciones y animaciones en el modal y página de novedades',
    ],
  },
  {
    version: '1.17.0',
    date: '12/07/2026',
    title: 'Next.js 16, Calidad y Performance',
    items: [
      'Upgrade Next.js 14 → 16.2 + React 19 con migración de breaking changes',
      'params async en 40+ API routes y generateMetadata, cookies() await',
      'Docker optimizado con BuildKit cache mounts y .dockerignore reducido',
      'Split schema.ts en 10 módulos por dominio (Fase 4 — Calidad de Código)',
      'DRY KPIs con config object, tipado strict (Session, MedicoDia, TurnoDia)',
      '38 tests nuevos con @vitest/coverage-v8',
      'Self-fetch → DB directo en dashboard stats (Fase 5 — Performance)',
      'CSS code-split: ~450 líneas movidas de globals.css a landing.css',
      'useOrganization hook para desduplicar carga de org',
      'Asistente IA toggle + sonido + fix sugerencias superpuestas',
    ],
  },
  {
    version: '1.16.0',
    date: '10/07/2026',
    title: 'UI Polish y Sistema de Diseño',
    items: [
      'Glassmorphism layer: CSS vars + utility classes en Card, Dialog, Sheet, KPIs',
      'Layout variations: 4 modos (default, wide, centered, minimal)',
      'Storybook con Vite 5: 5 stories core + portal stories',
      'Tooltips inteligentes con delay adaptativo (Radix + SmartTooltip)',
      '156 portal inline styles migrados a Tailwind',
      'Sidebar y header refactor: split en componentes más pequeños',
      '28 aria-labels adicionales en componentes del dashboard',
      'Dark mode portal con 3 colores semánticos',
      'Transiciones de página con framer-motion en dashboard',
      'Skip-to-content link y 8 portal spinners → skeletons',
    ],
  },
  {
    version: '1.15.0',
    date: '29/06/2026',
    title: 'Portal Analytics, Repositorio, Novedades y Tooltips',
    items: [
      'Portal Analytics: panel de Web Vitals con KPIs en tiempo real (LCP, INP, CLS, FCP, TTFB) y compliance score',
      'Gráficos interactivos: timeline horario/diario, heatmap 24h, bar chart de promedios, tabla por URL',
      'Filtros por sección (dashboard, portal, landing) y por dispositivo (mobile/desktop)',
      'Rendimiento Web: panel completo con percentiles, rating distribution, heatmap y tabla de URLs recientes',
      'Rating por color: thresholds de Google (good/needs-improvement/poor) aplicados en tiempo real',
      'Tooltips con nombre completo de métrica al hacer hover en gráficos, tabla y KPIs',
      'Fix "Invalid Date" en tooltips y leyendas de Recharts con guards en formatDate y formatBucket',
      'Página dedicada de Novedades en /dashboard/novedades con historial completo de versiones',
      'Link al repositorio de GitHub en el footer y sidebar para código fuente y contribuciones',
      'Sección Acerca de con versión, repo, changelog y enlaces útiles',
      'Ayuda expandida con nuevas secciones: Asistente IA Flotante, Command Palette, Portal Analytics',
      'Fix Ollama DEFINITIVO: maxDuration 120s, race-to-success, cold start 25s+ manejado correctamente',
      'Optimización de paquetes: framer-motion → motion standalone (4,621KB → 659KB)',
    ],
  },
  {
    version: '1.14.0',
    date: '28/06/2026',
    title: 'Asistente IA, Historial Lateral, Command Palette y Notificaciones Mejoradas',
    items: [
      'Asistente IA Flotante: FAB con Sparkles + panel de chat contextual en cualquier página del dashboard',
      '3 modos de asistente: Silencioso, Sugerente (cards de sugerencias) y Activo (chat libre con IA)',
      'Sugerencias contextuales inteligentes según la página actual (9 contextos distintos)',
      'Atajo Ctrl+Shift+I para abrir/cerrar el asistente rápidamente',
      'Historial Lateral de pacientes: Sheet con búsqueda fuzzy (fuse.js) de pacientes',
      'Resumen rápido del paciente: datos, alergias, turnos próximos, recetas activas, última nota SOAP',
      'Scoring dots visuales en búsqueda y resumen (riesgo de inasistencia)',
      'Acciones rápidas: ver ficha completa + WhatsApp directo desde el panel',
      'Atajo Ctrl+Shift+P para abrir el historial lateral',
      'Command Palette estilo Cmd+K con 17 navegación + 9 admin + 6 acciones rápidas',
      'Búsqueda paralela en 4 APIs (pacientes, turnos, recetas, mensajes) con debounce 250ms',
      'Feature gating + role gating en cada comando (admin vs no-admin)',
      'Notificaciones mejoradas: prioridad por tipo (urgencia > receta > turno > mensaje > sistema)',
      'Silenciar categorías: ocultar badges de tipos específicos de notificaciones',
      'Stack de mini-badges en el header con límite visible de 3 tipos + contador numérico',
      'Filtros por tipo con conteo en la página de notificaciones',
    ],
  },
  {
    version: '1.13.0',
    date: '27/06/2026',
    title: 'Rendimiento, Portal Analytics y Nuevos Precios',
    items: [
      'Server Components: 15 páginas migradas a SC wrapper + client islands para mejor performance',
      'Sistema de caché con revalidateTag: invalidate selectiva en 7 endpoints de API',
      'Web Vitals: migración 0041 + endpoint POST /api/web-vitals para métricas reales',
      'Portal Analytics: panel dedicado con KPIs del portal (LCP, INP, compliance, dispositivos)',
      'Section filter: filtra Web Vitals por sección (dashboard, portal, landing, all)',
      'Framer Motion → motion standalone: 4,621KB → 659KB (34 archivos migrados)',
      'Nuevos precios: Starter $79, Profesional $149, Premium $249, Enterprise $549',
      'Nuevo feature: scoring-pacientes disponible en Starter (predicción de inasistencia)',
      'Nuevo feature: web-vitals y portal-analytics en Premium',
      'Nuevo feature: carga-masiva de pacientes en Enterprise',
      'Nuevo feature: data-cache en Premium (caché inteligente con invalidación selectiva)',
    ],
  },
  {
    version: '1.12.0',
    date: '26/06/2026',
    title: 'Portal del Paciente + Cleanup',
    items: [
      'Portal del Paciente: magic link WhatsApp + JWT 24h + Booking Wizard 4 pasos',
      'Gestión de turnos, recetas e historial desde el portal',
      'Limpieza profunda del proyecto: dead code, archivos obsoletos, imports huérfanos',
      'Bad Gateway fix: standalone deps en Docker para build de producción',
    ],
  },
  {
    version: '1.11.0',
    date: '24/06/2026',
    title: 'Hardening de Seguridad',
    items: [
      'Webhook secret con timingSafeEqual en 3 endpoints (n8n, anonimizar, waitlist)',
      'Docker secrets para credenciales sensibles + env fallback',
      'CSP centralizado en proxy + headers COOP/COEP/CORP',
      'Rate limiting PostgreSQL en endpoints sensibles',
      'Migraciones productivas con permisos mínimos (revoca CREATE)',
      'CI: pnpm audit + Trivy scan + Dependabot (npm+docker+actions)',
    ],
  },
  {
    version: '1.10.0',
    date: '19/06/2026',
    title: 'Scoring de Pacientes, Seguridad y Conexión IA Real',
    items: [
      'Scoring automático de pacientes (0-100): algoritmo ponderado con no-shows x40, cancelaciones x25, confirmaciones x20, recordatorios x10, asistencia x5',
      'Badge de riesgo visual en lista de pacientes: verde (<40), amarillo (40-69), rojo (≥70)',
      'Bloqueo automático a lista negra: pacientes con score ≥80 y 2+ inasistencias',
      'Alertas de score alto integradas en panel lateral para médicos activos',
      'CSP Hardening: unsafe-eval solo en desarrollo, worker-src y media-src añadidos',
      'Cookie Consent: banner con 3 categorías (esencial/funcional/analytics) y hooks tipados',
      'Rate Limiting específico: register/forgot-password/reset-password/portal-auth (3-5 req/min)',
      'Logging seguro: webhooks Twilio y MercadoPago migrados a safeLog/safeWarn/safeError',
      'Onboarding IA: conexión real con Ollama Gemma3, health check previo, timeouts individuales (15s/intento, 45s global), keep_alive para modelo en memoria, fallback inmediato + loading sutil',
    ],
  },
  {
    version: '1.9.0',
    date: '14/06/2026',
    title: 'Telemedicina en Vivo con LiveKit',
    items: [
      'Telemedicina: videoconsultas en vivo con pacientes a través de LiveKit (self-hosted, sin costos por minuto)',
      'Nueva modalidad "Virtual" al crear turnos: el sistema genera automáticamente una sala de video y envía el link al paciente por WhatsApp',
      'Botón "Video" en el Kanban de Atención para iniciar videollamadas directo desde el panel',
      'Portal del Paciente: botón "Ingresar" para pacientes con turnos virtuales (link con token único)',
      'Feature gating: la telemedicina se habilita automáticamente en el plan Professional o superior',
      'Videollamada segura: tokens JWT temporales, sala privada médico-paciente, sin grabación',
      "Infraestructura: LiveKit server self-hosted en Dokploy con Redis, TURN, Ingress y HTTPS con Let's Encrypt",
      'Acceso multiplataforma: funciona en cualquier navegador moderno sin descargar apps',
      'Lista Negra de pacientes: gestioná restricciones de acceso al consultorio con registro de incidentes y control por tipo de restricción',
    ],
  },
  {
    version: '1.8.0',
    date: '13/06/2026',
    title: 'Derivaciones, Alertas Inteligentes y Rediseño Premium',
    items: [
      'Derivaciones entre especialistas: creá, aceptá, rechazá y completá interconsultas con notificaciones en tiempo real al médico destino',
      'Alertas inteligentes: detección automática de cumpleaños, ausentismo recurrente (2+ no asistencias en 30 días), y pacientes críticos (3+ consultas en 60 días)',
      'Temporizador de atención persistente: el tiempo de atención ahora se guarda en DB y sobrevive a recargas de página',
      'Rediseño Premium: animaciones suaves, cards con hover-lift, popovers con origen-aware, KPIs con count-up, sidebar con indicador activo y header glass',
      'Mejora en encuestas post-consulta con análisis de sentimiento usando IA local (Gemma3)',
      'CIE-10 expandido a ~1031 códigos con búsqueda mejorada',
      'Onboarding IA: progreso persistente, 6 etapas con re-ejecución y continuar más tarde',
      'Feature overrides por usuario: admin puede otorgar features de planes superiores a usuarios específicos',
    ],
  },
  {
    version: '1.7.0',
    date: '10/06/2026',
    title: 'Feature Overrides, Onboarding y CIE-10',
    items: [
      'Feature overrides por usuario: un admin puede habilitar features de planes superiores para usuarios específicos',
      'Onboarding IA: progreso persistente entre sesiones, re-ejecución del asistente, continuar más tarde',
      'Fix importancia: onboarding no se podía completar por error en paso 2; persistencia de pasos mejorada',
      'CIE-10 expandido con nuevos códigos comunes en Chile',
      'Encuestas post-consulta con análisis de sentimiento ML usando Gemma3',
    ],
  },
  {
    version: '1.6.0',
    date: '01/06/2026',
    title: 'Mejoras en Turnos, Recetas y Seguridad',
    items: [
      'Nuevo Turno desde la ficha del paciente con atajo de teclado Ctrl+T',
      'Certificados médicos: ahora funciona también para usuarios administradores',
      'Eliminación de recetas con confirmación (soft-delete a historial)',
      'Limpieza de workflows n8n duplicados',
    ],
  },
  {
    version: '1.5.0',
    date: '31/05/2026',
    title: 'Notas SOAP, Certificados QR y CIE-10',
    items: [
      'Notas SOAP: evolución clínica estructurada (Subjetivo, Objetivo, Assessment, Plan) con CIE-10 integrado en la ficha del paciente',
      'Certificados médicos con QR: hash SHA-256, verificación pública y descarga en PDF',
      'Buscador CIE-10 con autocomplete integrado en SOAP, historial y certificados',
      'Reportes con datos reales de la base de datos (4 tabs: ingresos, turnos, pacientes, recetas)',
    ],
  },
  {
    version: '1.4.0',
    date: '30/05/2026',
    title: 'Recordatorios y PWA',
    items: [
      'Recordatorios WhatsApp con confirmación/cancelación desde el mensaje',
      'Alerta al médico cuando un paciente cancela',
      'PWA: app instalable con modo offline y actualizaciones automáticas',
      'Diseño responsive: footer, sidebar, header y KPIs adaptados a mobile',
    ],
  },
  {
    version: '1.3.0',
    date: '29/05/2026',
    title: 'Firma Digital QR y Exportación',
    items: [
      'Firma digital QR en recetas con verificación pública',
      'Exportación de pacientes y recetas a Excel y PDF',
      'Múltiples médicos con agendas independientes',
      'Panel de monitoreo de automatizaciones',
    ],
  },
  {
    version: '1.2.0',
    date: '28/05/2026',
    title: 'Lista de Espera y Cancelaciones',
    items: [
      'Lista de espera inteligente con ofertas automáticas al cancelar turnos',
      'Cumplimiento ARCO: derecho de supresión, anonimización y retención configurable',
      'Panel de administración del sistema con feature toggles',
    ],
  },
  {
    version: '1.1.0',
    date: '27/05/2026',
    title: 'Asistente IA y Suscripciones',
    items: [
      'Onboarding asistido por IA con prompts contextuales',
      'Suscripciones vía MercadoPago con planes Free/Starter/Professional/Premium/Enterprise',
      'Google Calendar Sync bidireccional',
    ],
  },
  {
    version: '1.0.0',
    date: '25/05/2026',
    title: 'Lanzamiento',
    items: [
      'Dashboard con KPIs en tiempo real',
      'Gestión de turnos con agenda y Kanban de atención',
      'Ficha de pacientes con historial clínico',
      'Recetas digitales con envío por WhatsApp',
      'Conversaciones WhatsApp con pacientes',
      'Autenticación 2FA',
    ],
  },
];
