// ─── CIE-10: Códigos más usados en consultorio médico ──────
// ~350 códigos de las categorías más frecuentes en atención primaria

export interface Cie10Entry {
  codigo: string;
  descripcion: string;
  categoria: string;
}

export const CIE10_DATA: Cie10Entry[] = [
  // A - Infecciosas
  { codigo: 'A09', descripcion: 'Gastroenteritis infecciosa', categoria: 'Infecciosas' },
  { codigo: 'A15', descripcion: 'Tuberculosis respiratoria', categoria: 'Infecciosas' },
  { codigo: 'A36', descripcion: 'Difteria', categoria: 'Infecciosas' },
  { codigo: 'A37', descripcion: 'Tos ferina', categoria: 'Infecciosas' },
  { codigo: 'A38', descripcion: 'Escarlatina', categoria: 'Infecciosas' },
  { codigo: 'A46', descripcion: 'Erisipela', categoria: 'Infecciosas' },
  { codigo: 'A49', descripcion: 'Infección bacteriana no especificada', categoria: 'Infecciosas' },
  { codigo: 'A54', descripcion: 'Infección gonocócica', categoria: 'ITS' },
  { codigo: 'A59', descripcion: 'Tricomoniasis', categoria: 'ITS' },
  { codigo: 'A60', descripcion: 'Herpes anogenital', categoria: 'ITS' },
  { codigo: 'A63', descripcion: 'Otras ETS', categoria: 'ITS' },
  { codigo: 'A64', descripcion: 'ETS no especificada', categoria: 'ITS' },

  // B - Virales / Parasitarias
  { codigo: 'B00', descripcion: 'Herpes simple', categoria: 'Virales' },
  { codigo: 'B01', descripcion: 'Varicela', categoria: 'Virales' },
  { codigo: 'B02', descripcion: 'Herpes zóster', categoria: 'Virales' },
  { codigo: 'B05', descripcion: 'Sarampión', categoria: 'Virales' },
  { codigo: 'B06', descripcion: 'Rubéola', categoria: 'Virales' },
  { codigo: 'B07', descripcion: 'Verrugas virales', categoria: 'Virales' },
  { codigo: 'B15', descripcion: 'Hepatitis A aguda', categoria: 'Hepatitis' },
  { codigo: 'B16', descripcion: 'Hepatitis B aguda', categoria: 'Hepatitis' },
  { codigo: 'B18', descripcion: 'Hepatitis viral crónica', categoria: 'Hepatitis' },
  { codigo: 'B20', descripcion: 'VIH con infecciones', categoria: 'VIH' },
  { codigo: 'B24', descripcion: 'VIH no especificado', categoria: 'VIH' },
  { codigo: 'B26', descripcion: 'Paperas', categoria: 'Virales' },
  { codigo: 'B27', descripcion: 'Mononucleosis', categoria: 'Virales' },
  { codigo: 'B30', descripcion: 'Conjuntivitis viral', categoria: 'Virales' },
  { codigo: 'B34', descripcion: 'Infección viral sin especificar', categoria: 'Virales' },
  { codigo: 'B35', descripcion: 'Dermatofitosis (hongos piel)', categoria: 'Micosis' },
  { codigo: 'B36', descripcion: 'Otras micosis superficiales', categoria: 'Micosis' },
  { codigo: 'B37', descripcion: 'Candidiasis', categoria: 'Micosis' },
  { codigo: 'B57', descripcion: 'Enfermedad de Chagas', categoria: 'Parasitosis' },
  { codigo: 'B58', descripcion: 'Toxoplasmosis', categoria: 'Parasitosis' },
  { codigo: 'B65', descripcion: 'Esquistosomiasis', categoria: 'Parasitosis' },
  { codigo: 'B76', descripcion: 'Anquilostomiasis', categoria: 'Parasitosis' },
  { codigo: 'B77', descripcion: 'Ascariasis', categoria: 'Parasitosis' },
  { codigo: 'B80', descripcion: 'Oxiuriasis (enterobiasis)', categoria: 'Parasitosis' },
  { codigo: 'B85', descripcion: 'Pediculosis (piojos)', categoria: 'Parasitosis' },
  { codigo: 'B86', descripcion: 'Escabiosis (sarna)', categoria: 'Parasitosis' },
  { codigo: 'B95', descripcion: 'Estreptococo como causa', categoria: 'Causas' },
  { codigo: 'B96', descripcion: 'Otros agentes bacterianos', categoria: 'Causas' },
  { codigo: 'B97', descripcion: 'Agentes virales como causa', categoria: 'Causas' },

  // C - Neoplasias (más frecuentes)
  { codigo: 'C16', descripcion: 'Neoplasia maligna de estómago', categoria: 'Neoplasias' },
  { codigo: 'C18', descripcion: 'Neoplasia maligna de colon', categoria: 'Neoplasias' },
  { codigo: 'C20', descripcion: 'Neoplasia maligna de recto', categoria: 'Neoplasias' },
  { codigo: 'C22', descripcion: 'Neoplasia maligna de hígado', categoria: 'Neoplasias' },
  { codigo: 'C25', descripcion: 'Neoplasia maligna de páncreas', categoria: 'Neoplasias' },
  { codigo: 'C32', descripcion: 'Neoplasia maligna de laringe', categoria: 'Neoplasias' },
  { codigo: 'C34', descripcion: 'Neoplasia maligna de pulmón', categoria: 'Neoplasias' },
  { codigo: 'C43', descripcion: 'Melanoma maligno', categoria: 'Neoplasias' },
  { codigo: 'C44', descripcion: 'Otras neoplasias de piel', categoria: 'Neoplasias' },
  { codigo: 'C50', descripcion: 'Neoplasia maligna de mama', categoria: 'Neoplasias' },
  { codigo: 'C53', descripcion: 'Neoplasia maligna de cuello uterino', categoria: 'Neoplasias' },
  { codigo: 'C54', descripcion: 'Neoplasia maligna de cuerpo uterino', categoria: 'Neoplasias' },
  { codigo: 'C56', descripcion: 'Neoplasia maligna de ovario', categoria: 'Neoplasias' },
  { codigo: 'C61', descripcion: 'Neoplasia maligna de próstata', categoria: 'Neoplasias' },
  { codigo: 'C62', descripcion: 'Neoplasia maligna de testículo', categoria: 'Neoplasias' },
  { codigo: 'C64', descripcion: 'Neoplasia maligna de riñón', categoria: 'Neoplasias' },
  { codigo: 'C67', descripcion: 'Neoplasia maligna de vejiga', categoria: 'Neoplasias' },
  { codigo: 'C71', descripcion: 'Neoplasia maligna de encéfalo', categoria: 'Neoplasias' },
  { codigo: 'C73', descripcion: 'Neoplasia maligna de tiroides', categoria: 'Neoplasias' },
  { codigo: 'C81', descripcion: 'Enfermedad de Hodgkin', categoria: 'Linfomas' },
  { codigo: 'C82', descripcion: 'Linfoma no Hodgkin folicular', categoria: 'Linfomas' },
  { codigo: 'C85', descripcion: 'Linfoma no Hodgkin otro tipo', categoria: 'Linfomas' },
  { codigo: 'C90', descripcion: 'Mieloma múltiple', categoria: 'Neoplasias' },
  { codigo: 'C91', descripcion: 'Leucemia linfoide', categoria: 'Leucemias' },
  { codigo: 'C92', descripcion: 'Leucemia mieloide', categoria: 'Leucemias' },
  { codigo: 'D10', descripcion: 'Neoplasia benigna de boca', categoria: 'Benignas' },
  { codigo: 'D12', descripcion: 'Neoplasia benigna de colon', categoria: 'Benignas' },
  { codigo: 'D17', descripcion: 'Lipoma', categoria: 'Benignas' },
  { codigo: 'D18', descripcion: 'Hemangioma', categoria: 'Benignas' },
  { codigo: 'D22', descripcion: 'Nevus melanocítico (lunar)', categoria: 'Benignas' },
  { codigo: 'D23', descripcion: 'Neoplasia benigna de piel', categoria: 'Benignas' },
  { codigo: 'D24', descripcion: 'Neoplasia benigna de mama', categoria: 'Benignas' },
  { codigo: 'D25', descripcion: 'Leiomioma uterino (fibroma)', categoria: 'Benignas' },
  { codigo: 'D27', descripcion: 'Neoplasia benigna de ovario', categoria: 'Benignas' },
  { codigo: 'D34', descripcion: 'Neoplasia benigna de tiroides', categoria: 'Benignas' },

  // E - Endocrinas / Metabólicas
  { codigo: 'E03', descripcion: 'Hipotiroidismo', categoria: 'Tiroides' },
  { codigo: 'E04', descripcion: 'Bocio no tóxico', categoria: 'Tiroides' },
  { codigo: 'E05', descripcion: 'Hipertiroidismo', categoria: 'Tiroides' },
  { codigo: 'E06', descripcion: 'Tiroiditis', categoria: 'Tiroides' },
  { codigo: 'E07', descripcion: 'Otros trastornos tiroideos', categoria: 'Tiroides' },
  { codigo: 'E10', descripcion: 'Diabetes tipo 1', categoria: 'Diabetes' },
  { codigo: 'E11', descripcion: 'Diabetes tipo 2', categoria: 'Diabetes' },
  { codigo: 'E14', descripcion: 'Diabetes no especificada', categoria: 'Diabetes' },
  { codigo: 'E16', descripcion: 'Hipoglucemia', categoria: 'Metabólicas' },
  { codigo: 'E21', descripcion: 'Hiperparatiroidismo', categoria: 'Endocrinas' },
  { codigo: 'E22', descripcion: 'Hiperfunción hipofisaria', categoria: 'Endocrinas' },
  { codigo: 'E24', descripcion: 'Síndrome de Cushing', categoria: 'Endocrinas' },
  { codigo: 'E26', descripcion: 'Hiperaldosteronismo', categoria: 'Endocrinas' },
  { codigo: 'E28', descripcion: 'Disfunción ovárica', categoria: 'Endocrinas' },
  { codigo: 'E29', descripcion: 'Disfunción testicular', categoria: 'Endocrinas' },
  { codigo: 'E34', descripcion: 'Otros trastornos endocrinos', categoria: 'Endocrinas' },
  { codigo: 'E44', descripcion: 'Desnutrición moderada', categoria: 'Nutrición' },
  { codigo: 'E46', descripcion: 'Desnutrición no especificada', categoria: 'Nutrición' },
  { codigo: 'E53', descripcion: 'Deficiencia de vitaminas B', categoria: 'Nutrición' },
  { codigo: 'E55', descripcion: 'Deficiencia de vitamina D', categoria: 'Nutrición' },
  { codigo: 'E61', descripcion: 'Deficiencia de zinc', categoria: 'Nutrición' },
  { codigo: 'E66', descripcion: 'Obesidad', categoria: 'Metabólicas' },
  { codigo: 'E73', descripcion: 'Intolerancia a la lactosa', categoria: 'Metabólicas' },
  { codigo: 'E78', descripcion: 'Hiperlipidemia (colesterol alto)', categoria: 'Metabólicas' },
  { codigo: 'E79', descripcion: 'Hiperuricemia (ácido úrico)', categoria: 'Metabólicas' },
  { codigo: 'E84', descripcion: 'Fibrosis quística', categoria: 'Metabólicas' },
  { codigo: 'E86', descripcion: 'Deshidratación', categoria: 'Metabólicas' },
  { codigo: 'E87', descripcion: 'Desequilibrio hidroelectrolítico', categoria: 'Metabólicas' },

  // F - Salud Mental
  { codigo: 'F00', descripcion: 'Demencia Alzheimer', categoria: 'Demencia' },
  { codigo: 'F01', descripcion: 'Demencia vascular', categoria: 'Demencia' },
  { codigo: 'F03', descripcion: 'Demencia no especificada', categoria: 'Demencia' },
  { codigo: 'F05', descripcion: 'Delirio', categoria: 'Orgánicos' },
  { codigo: 'F10', descripcion: 'Alcoholismo', categoria: 'Sustancias' },
  { codigo: 'F12', descripcion: 'Trastorno por cannabis', categoria: 'Sustancias' },
  { codigo: 'F17', descripcion: 'Tabaquismo', categoria: 'Sustancias' },
  { codigo: 'F20', descripcion: 'Esquizofrenia', categoria: 'Psicóticos' },
  { codigo: 'F22', descripcion: 'Trastorno delirante', categoria: 'Psicóticos' },
  { codigo: 'F23', descripcion: 'Psicosis aguda', categoria: 'Psicóticos' },
  { codigo: 'F25', descripcion: 'Trastorno esquizoafectivo', categoria: 'Psicóticos' },
  { codigo: 'F31', descripcion: 'Trastorno bipolar', categoria: 'Ánimo' },
  { codigo: 'F32', descripcion: 'Depresión mayor', categoria: 'Ánimo' },
  { codigo: 'F33', descripcion: 'Depresión recurrente', categoria: 'Ánimo' },
  { codigo: 'F34', descripcion: 'Distimia', categoria: 'Ánimo' },
  { codigo: 'F40', descripcion: 'Fobias', categoria: 'Ansiedad' },
  { codigo: 'F41', descripcion: 'Trastorno de ansiedad', categoria: 'Ansiedad' },
  { codigo: 'F42', descripcion: 'TOC', categoria: 'Ansiedad' },
  { codigo: 'F43', descripcion: 'Trastorno por estrés', categoria: 'Ansiedad' },
  { codigo: 'F44', descripcion: 'Trastorno disociativo', categoria: 'Somatoformes' },
  { codigo: 'F45', descripcion: 'Trastorno somatomorfo', categoria: 'Somatoformes' },
  { codigo: 'F50', descripcion: 'Trastorno alimentario', categoria: 'Alimentarios' },
  { codigo: 'F51', descripcion: 'Insomnio no orgánico', categoria: 'Sueño' },
  { codigo: 'F60', descripcion: 'Trastorno de personalidad', categoria: 'Personalidad' },
  { codigo: 'F70', descripcion: 'Retraso mental leve', categoria: 'Discapacidad' },
  { codigo: 'F79', descripcion: 'Retraso mental no especificado', categoria: 'Discapacidad' },
  { codigo: 'F80', descripcion: 'Trastorno del habla', categoria: 'Desarrollo' },
  { codigo: 'F81', descripcion: 'Trastorno del aprendizaje', categoria: 'Desarrollo' },
  { codigo: 'F84', descripcion: 'TEA (autismo)', categoria: 'Desarrollo' },
  { codigo: 'F90', descripcion: 'TDAH', categoria: 'Infancia' },
  { codigo: 'F91', descripcion: 'Trastorno de conducta', categoria: 'Infancia' },
  { codigo: 'F95', descripcion: 'Tics', categoria: 'Infancia' },
  { codigo: 'F99', descripcion: 'Trastorno mental no especificado', categoria: 'Otros' },

  // G - Sistema Nervioso
  { codigo: 'G03', descripcion: 'Meningitis no bacteriana', categoria: 'SNC' },
  { codigo: 'G04', descripcion: 'Encefalitis', categoria: 'SNC' },
  { codigo: 'G20', descripcion: 'Parkinson', categoria: 'Neurodegenerativas' },
  { codigo: 'G24', descripcion: 'Distonía', categoria: 'Movimiento' },
  { codigo: 'G25', descripcion: 'Otros trastornos del movimiento', categoria: 'Movimiento' },
  { codigo: 'G30', descripcion: 'Alzheimer', categoria: 'Neurodegenerativas' },
  { codigo: 'G35', descripcion: 'Esclerosis múltiple', categoria: 'Desmielinizantes' },
  { codigo: 'G40', descripcion: 'Epilepsia', categoria: 'Epilepsia' },
  { codigo: 'G41', descripcion: 'Estado epiléptico', categoria: 'Epilepsia' },
  { codigo: 'G43', descripcion: 'Migraña', categoria: 'Cefaleas' },
  { codigo: 'G44', descripcion: 'Otras cefaleas', categoria: 'Cefaleas' },
  { codigo: 'G45', descripcion: 'AIT (ataque isquémico transitorio)', categoria: 'Vascular' },
  { codigo: 'G47', descripcion: 'Trastornos del sueño', categoria: 'Sueño' },
  { codigo: 'G50', descripcion: 'Neuralgia del trigémino', categoria: 'Nervios' },
  { codigo: 'G51', descripcion: 'Parálisis facial (Bell)', categoria: 'Nervios' },
  { codigo: 'G54', descripcion: 'Trastornos de raíces nerviosas', categoria: 'Nervios' },
  { codigo: 'G56', descripcion: 'Síndrome del túnel carpiano', categoria: 'Nervios' },
  { codigo: 'G57', descripcion: 'Ciática', categoria: 'Nervios' },
  { codigo: 'G60', descripcion: 'Neuropatía hereditaria', categoria: 'Neuropatías' },
  { codigo: 'G62', descripcion: 'Polineuropatía', categoria: 'Neuropatías' },
  { codigo: 'G70', descripcion: 'Miastenia gravis', categoria: 'Musculares' },
  { codigo: 'G80', descripcion: 'Parálisis cerebral', categoria: 'Parálisis' },
  { codigo: 'G81', descripcion: 'Hemiplejía', categoria: 'Parálisis' },
  { codigo: 'G82', descripcion: 'Paraplejía', categoria: 'Parálisis' },
  { codigo: 'G91', descripcion: 'Hidrocefalia', categoria: 'SNC' },
  { codigo: 'G93', descripcion: 'Otros trastornos del encéfalo', categoria: 'SNC' },

  // H - Oftalmología / Otorrinolaringología
  { codigo: 'H00', descripcion: 'Orzuelo', categoria: 'Oftalmología' },
  { codigo: 'H01', descripcion: 'Blefaritis', categoria: 'Oftalmología' },
  { codigo: 'H04', descripcion: 'Obstrucción lagrimal', categoria: 'Oftalmología' },
  { codigo: 'H10', descripcion: 'Conjuntivitis', categoria: 'Oftalmología' },
  { codigo: 'H15', descripcion: 'Escleritis', categoria: 'Oftalmología' },
  { codigo: 'H16', descripcion: 'Queratitis', categoria: 'Oftalmología' },
  { codigo: 'H20', descripcion: 'Iritis / uveítis', categoria: 'Oftalmología' },
  { codigo: 'H25', descripcion: 'Catarata', categoria: 'Oftalmología' },
  { codigo: 'H33', descripcion: 'Desprendimiento de retina', categoria: 'Oftalmología' },
  { codigo: 'H35', descripcion: 'Retinopatía', categoria: 'Oftalmología' },
  { codigo: 'H40', descripcion: 'Glaucoma', categoria: 'Oftalmología' },
  { codigo: 'H46', descripcion: 'Neuritis óptica', categoria: 'Oftalmología' },
  { codigo: 'H52', descripcion: 'Vicios de refracción', categoria: 'Oftalmología' },
  { codigo: 'H53', descripcion: 'Alteraciones de la visión', categoria: 'Oftalmología' },
  { codigo: 'H54', descripcion: 'Ceguera / baja visión', categoria: 'Oftalmología' },
  { codigo: 'H60', descripcion: 'Otitis externa', categoria: 'Otorrino' },
  { codigo: 'H61', descripcion: 'Otros trastornos oído externo', categoria: 'Otorrino' },
  { codigo: 'H65', descripcion: 'Otitis media serosa', categoria: 'Otorrino' },
  { codigo: 'H66', descripcion: 'Otitis media supurativa', categoria: 'Otorrino' },
  { codigo: 'H68', descripcion: 'Disfunción trompa Eustaquio', categoria: 'Otorrino' },
  { codigo: 'H70', descripcion: 'Mastoiditis', categoria: 'Otorrino' },
  { codigo: 'H72', descripcion: 'Perforación timpánica', categoria: 'Otorrino' },
  { codigo: 'H81', descripcion: 'Vértigo / laberintitis', categoria: 'Otorrino' },
  { codigo: 'H90', descripcion: 'Hipoacusia', categoria: 'Otorrino' },
  { codigo: 'H91', descripcion: 'Hipoacusia otras', categoria: 'Otorrino' },
  { codigo: 'H92', descripcion: 'Otalgia', categoria: 'Otorrino' },

  // I - Cardiovasculares
  { codigo: 'I10', descripcion: 'Hipertensión arterial esencial', categoria: 'HTA' },
  { codigo: 'I11', descripcion: 'Cardiopatía hipertensiva', categoria: 'HTA' },
  { codigo: 'I12', descripcion: 'Nefropatía hipertensiva', categoria: 'HTA' },
  { codigo: 'I15', descripcion: 'Hipertensión secundaria', categoria: 'HTA' },
  { codigo: 'I20', descripcion: 'Angina de pecho', categoria: 'Cardiopatías' },
  { codigo: 'I21', descripcion: 'Infarto agudo de miocardio', categoria: 'Cardiopatías' },
  { codigo: 'I25', descripcion: 'Cardiopatía isquémica crónica', categoria: 'Cardiopatías' },
  { codigo: 'I26', descripcion: 'Embolia pulmonar', categoria: 'Cardiopatías' },
  { codigo: 'I30', descripcion: 'Pericarditis aguda', categoria: 'Cardiopatías' },
  { codigo: 'I33', descripcion: 'Endocarditis', categoria: 'Cardiopatías' },
  { codigo: 'I34', descripcion: 'Trastorno válvula mitral', categoria: 'Cardiopatías' },
  { codigo: 'I35', descripcion: 'Trastorno válvula aórtica', categoria: 'Cardiopatías' },
  { codigo: 'I40', descripcion: 'Miocarditis', categoria: 'Cardiopatías' },
  { codigo: 'I42', descripcion: 'Miocardiopatía', categoria: 'Cardiopatías' },
  { codigo: 'I44', descripcion: 'Bloqueo AV', categoria: 'Arritmias' },
  { codigo: 'I45', descripcion: 'Otros trastornos conducción', categoria: 'Arritmias' },
  { codigo: 'I46', descripcion: 'Paro cardíaco', categoria: 'Arritmias' },
  { codigo: 'I47', descripcion: 'Taquicardia', categoria: 'Arritmias' },
  { codigo: 'I48', descripcion: 'Fibrilación auricular', categoria: 'Arritmias' },
  { codigo: 'I49', descripcion: 'Otras arritmias', categoria: 'Arritmias' },
  { codigo: 'I50', descripcion: 'Insuficiencia cardíaca', categoria: 'Cardiopatías' },
  { codigo: 'I60', descripcion: 'Hemorragia subaracnoidea', categoria: 'ACV' },
  { codigo: 'I61', descripcion: 'Hemorragia intracerebral', categoria: 'ACV' },
  { codigo: 'I63', descripcion: 'Infarto cerebral (ACV isquémico)', categoria: 'ACV' },
  { codigo: 'I64', descripcion: 'ACV no especificado', categoria: 'ACV' },
  { codigo: 'I67', descripcion: 'Otras enfermedades cerebrovasculares', categoria: 'ACV' },
  { codigo: 'I69', descripcion: 'Secuelas de ACV', categoria: 'ACV' },
  { codigo: 'I70', descripcion: 'Aterosclerosis', categoria: 'Vascular' },
  { codigo: 'I71', descripcion: 'Aneurisma aórtico', categoria: 'Vascular' },
  { codigo: 'I73', descripcion: 'Enfermedad vascular periférica', categoria: 'Vascular' },
  { codigo: 'I74', descripcion: 'Embolia arterial', categoria: 'Vascular' },
  { codigo: 'I80', descripcion: 'Tromboflebitis', categoria: 'Vascular' },
  { codigo: 'I82', descripcion: 'Embolia pulmonar', categoria: 'Vascular' },
  { codigo: 'I83', descripcion: 'Várices', categoria: 'Vascular' },
  { codigo: 'I84', descripcion: 'Hemorroides', categoria: 'Vascular' },
  { codigo: 'I88', descripcion: 'Linfadenitis', categoria: 'Vascular' },
  { codigo: 'I95', descripcion: 'Hipotensión', categoria: 'Cardiopatías' },

  // J - Respiratorias
  { codigo: 'J00', descripcion: 'Resfriado común', categoria: 'Respiratorio' },
  { codigo: 'J01', descripcion: 'Sinusitis aguda', categoria: 'Respiratorio' },
  { codigo: 'J02', descripcion: 'Faringitis aguda', categoria: 'Respiratorio' },
  { codigo: 'J03', descripcion: 'Amigdalitis aguda', categoria: 'Respiratorio' },
  { codigo: 'J04', descripcion: 'Laringitis aguda', categoria: 'Respiratorio' },
  { codigo: 'J06', descripcion: 'Infección respiratoria alta', categoria: 'Respiratorio' },
  { codigo: 'J09', descripcion: 'Influenza (gripe)', categoria: 'Respiratorio' },
  { codigo: 'J11', descripcion: 'Influenza no especificada', categoria: 'Respiratorio' },
  { codigo: 'J12', descripcion: 'Neumonía viral', categoria: 'Respiratorio' },
  { codigo: 'J13', descripcion: 'Neumonía neumocócica', categoria: 'Respiratorio' },
  { codigo: 'J15', descripcion: 'Neumonía bacteriana', categoria: 'Respiratorio' },
  { codigo: 'J18', descripcion: 'Neumonía no especificada', categoria: 'Respiratorio' },
  { codigo: 'J20', descripcion: 'Bronquitis aguda', categoria: 'Respiratorio' },
  { codigo: 'J21', descripcion: 'Bronquiolitis', categoria: 'Respiratorio' },
  { codigo: 'J22', descripcion: 'Infección respiratoria baja', categoria: 'Respiratorio' },
  { codigo: 'J30', descripcion: 'Rinitis alérgica', categoria: 'Respiratorio' },
  { codigo: 'J31', descripcion: 'Rinitis crónica', categoria: 'Respiratorio' },
  { codigo: 'J32', descripcion: 'Sinusitis crónica', categoria: 'Respiratorio' },
  { codigo: 'J33', descripcion: 'Pólipo nasal', categoria: 'Respiratorio' },
  { codigo: 'J34', descripcion: 'Otros trastornos nasales', categoria: 'Respiratorio' },
  { codigo: 'J35', descripcion: 'Hipertrofia amigdalina', categoria: 'Respiratorio' },
  { codigo: 'J37', descripcion: 'Laringitis crónica', categoria: 'Respiratorio' },
  { codigo: 'J38', descripcion: 'Parálisis cuerdas vocales', categoria: 'Respiratorio' },
  { codigo: 'J40', descripcion: 'Bronquitis no especificada', categoria: 'Respiratorio' },
  { codigo: 'J42', descripcion: 'Bronquitis crónica', categoria: 'Respiratorio' },
  { codigo: 'J43', descripcion: 'Enfisema', categoria: 'Respiratorio' },
  { codigo: 'J44', descripcion: 'EPOC', categoria: 'Respiratorio' },
  { codigo: 'J45', descripcion: 'Asma', categoria: 'Respiratorio' },
  { codigo: 'J46', descripcion: 'Estado asmático', categoria: 'Respiratorio' },
  { codigo: 'J47', descripcion: 'Bronquiectasias', categoria: 'Respiratorio' },
  { codigo: 'J80', descripcion: 'Síndrome dificultad respiratoria', categoria: 'Respiratorio' },
  { codigo: 'J81', descripcion: 'Edema pulmonar', categoria: 'Respiratorio' },
  { codigo: 'J84', descripcion: 'Enfermedad pulmonar intersticial', categoria: 'Respiratorio' },
  { codigo: 'J85', descripcion: 'Absceso pulmonar', categoria: 'Respiratorio' },
  { codigo: 'J86', descripcion: 'Piotórax / empiema', categoria: 'Respiratorio' },
  { codigo: 'J90', descripcion: 'Derrame pleural', categoria: 'Respiratorio' },
  { codigo: 'J93', descripcion: 'Neumotórax', categoria: 'Respiratorio' },
  { codigo: 'J96', descripcion: 'Insuficiencia respiratoria', categoria: 'Respiratorio' },
  { codigo: 'J98', descripcion: 'Otros trastornos respiratorios', categoria: 'Respiratorio' },

  // K - Digestivas
  { codigo: 'K02', descripcion: 'Caries dental', categoria: 'Digestivo' },
  { codigo: 'K04', descripcion: 'Enfermedad pulpar', categoria: 'Digestivo' },
  { codigo: 'K05', descripcion: 'Gingivitis', categoria: 'Digestivo' },
  { codigo: 'K08', descripcion: 'Pérdida dental', categoria: 'Digestivo' },
  { codigo: 'K12', descripcion: 'Estomatitis aftosa', categoria: 'Digestivo' },
  { codigo: 'K20', descripcion: 'Esofagitis', categoria: 'Digestivo' },
  { codigo: 'K21', descripcion: 'Reflujo gastroesofágico', categoria: 'Digestivo' },
  { codigo: 'K22', descripcion: 'Acalasia / otros esófago', categoria: 'Digestivo' },
  { codigo: 'K25', descripcion: 'Úlcera gástrica', categoria: 'Digestivo' },
  { codigo: 'K26', descripcion: 'Úlcera duodenal', categoria: 'Digestivo' },
  { codigo: 'K27', descripcion: 'Úlcera péptica', categoria: 'Digestivo' },
  { codigo: 'K29', descripcion: 'Gastritis / duodenitis', categoria: 'Digestivo' },
  { codigo: 'K30', descripcion: 'Dispepsia funcional', categoria: 'Digestivo' },
  { codigo: 'K31', descripcion: 'Otros trastornos estómago', categoria: 'Digestivo' },
  { codigo: 'K35', descripcion: 'Apendicitis aguda', categoria: 'Digestivo' },
  { codigo: 'K36', descripcion: 'Apendicitis crónica', categoria: 'Digestivo' },
  { codigo: 'K40', descripcion: 'Hernia inguinal', categoria: 'Digestivo' },
  { codigo: 'K42', descripcion: 'Hernia umbilical', categoria: 'Digestivo' },
  { codigo: 'K44', descripcion: 'Hernia hiatal', categoria: 'Digestivo' },
  { codigo: 'K50', descripcion: 'Enfermedad de Crohn', categoria: 'Digestivo' },
  { codigo: 'K51', descripcion: 'Colitis ulcerosa', categoria: 'Digestivo' },
  { codigo: 'K52', descripcion: 'Colitis no infecciosa', categoria: 'Digestivo' },
  { codigo: 'K56', descripcion: 'Ileo paralítico / obstrucción', categoria: 'Digestivo' },
  { codigo: 'K57', descripcion: 'Diverticulosis / diverticulitis', categoria: 'Digestivo' },
  { codigo: 'K58', descripcion: 'SII (intestino irritable)', categoria: 'Digestivo' },
  { codigo: 'K59', descripcion: 'Estreñimiento', categoria: 'Digestivo' },
  { codigo: 'K60', descripcion: 'Fisura anal', categoria: 'Digestivo' },
  { codigo: 'K61', descripcion: 'Absceso anal / fístula', categoria: 'Digestivo' },
  { codigo: 'K63', descripcion: 'Otras enfermedades intestinales', categoria: 'Digestivo' },
  { codigo: 'K65', descripcion: 'Peritonitis', categoria: 'Digestivo' },
  { codigo: 'K70', descripcion: 'Hígado graso alcohólico', categoria: 'Hepatología' },
  { codigo: 'K71', descripcion: 'Hepatopatía tóxica', categoria: 'Hepatología' },
  { codigo: 'K72', descripcion: 'Insuficiencia hepática', categoria: 'Hepatología' },
  { codigo: 'K73', descripcion: 'Hepatitis crónica', categoria: 'Hepatología' },
  { codigo: 'K74', descripcion: 'Fibrosis / cirrosis', categoria: 'Hepatología' },
  { codigo: 'K75', descripcion: 'Otras hepatitis', categoria: 'Hepatología' },
  { codigo: 'K76', descripcion: 'Hígado graso no alcohólico', categoria: 'Hepatología' },
  { codigo: 'K80', descripcion: 'Colelitiasis (cálculos biliares)', categoria: 'Hepatología' },
  { codigo: 'K81', descripcion: 'Colecistitis', categoria: 'Hepatología' },
  { codigo: 'K82', descripcion: 'Otros trastornos vesícula', categoria: 'Hepatología' },
  { codigo: 'K85', descripcion: 'Pancreatitis aguda', categoria: 'Digestivo' },
  { codigo: 'K86', descripcion: 'Pancreatitis crónica', categoria: 'Digestivo' },
  { codigo: 'K90', descripcion: 'Malabsorción', categoria: 'Digestivo' },
  { codigo: 'K92', descripcion: 'Otros trastornos digestivos', categoria: 'Digestivo' },

  // L - Piel
  { codigo: 'L01', descripcion: 'Impétigo', categoria: 'Piel' },
  { codigo: 'L02', descripcion: 'Absceso cutáneo', categoria: 'Piel' },
  { codigo: 'L03', descripcion: 'Celulitis', categoria: 'Piel' },
  { codigo: 'L05', descripcion: 'Quiste pilonidal', categoria: 'Piel' },
  { codigo: 'L08', descripcion: 'Otras infecciones piel', categoria: 'Piel' },
  { codigo: 'L10', descripcion: 'Pénfigo', categoria: 'Piel' },
  { codigo: 'L20', descripcion: 'Dermatitis atópica (eczema)', categoria: 'Piel' },
  { codigo: 'L21', descripcion: 'Dermatitis seborreica', categoria: 'Piel' },
  { codigo: 'L22', descripcion: 'Dermatitis del pañal', categoria: 'Piel' },
  { codigo: 'L23', descripcion: 'Dermatitis alérgica contacto', categoria: 'Piel' },
  { codigo: 'L24', descripcion: 'Dermatitis irritativa', categoria: 'Piel' },
  { codigo: 'L25', descripcion: 'Dermatitis contacto no especificada', categoria: 'Piel' },
  { codigo: 'L27', descripcion: 'Alergia cutánea por medicamentos', categoria: 'Piel' },
  { codigo: 'L28', descripcion: 'Liquen simple crónico', categoria: 'Piel' },
  { codigo: 'L29', descripcion: 'Prurito (picazón)', categoria: 'Piel' },
  { codigo: 'L30', descripcion: 'Otras dermatitis', categoria: 'Piel' },
  { codigo: 'L40', descripcion: 'Psoriasis', categoria: 'Piel' },
  { codigo: 'L42', descripcion: 'Pitiriasis rosada', categoria: 'Piel' },
  { codigo: 'L43', descripcion: 'Liquen plano', categoria: 'Piel' },
  { codigo: 'L50', descripcion: 'Urticaria (ronchas)', categoria: 'Piel' },
  { codigo: 'L51', descripcion: 'Eritema multiforme', categoria: 'Piel' },
  { codigo: 'L52', descripcion: 'Eritema nudoso', categoria: 'Piel' },
  { codigo: 'L55', descripcion: 'Quemadura solar', categoria: 'Piel' },
  { codigo: 'L57', descripcion: 'Fotoenvejecimiento', categoria: 'Piel' },
  { codigo: 'L60', descripcion: 'Trastornos de uñas', categoria: 'Piel' },
  { codigo: 'L63', descripcion: 'Alopecia areata', categoria: 'Piel' },
  { codigo: 'L64', descripcion: 'Calvicie (alopecia androgénica)', categoria: 'Piel' },
  { codigo: 'L65', descripcion: 'Otras alopecias', categoria: 'Piel' },
  { codigo: 'L70', descripcion: 'Acné', categoria: 'Piel' },
  { codigo: 'L71', descripcion: 'Rosácea', categoria: 'Piel' },
  { codigo: 'L72', descripcion: 'Quiste folicular', categoria: 'Piel' },
  { codigo: 'L80', descripcion: 'Vitíligo', categoria: 'Piel' },
  { codigo: 'L81', descripcion: 'Otros trastornos pigmentación', categoria: 'Piel' },
  { codigo: 'L82', descripcion: 'Queratosis seborreica', categoria: 'Piel' },
  { codigo: 'L84', descripcion: 'Callos / durezas', categoria: 'Piel' },
  { codigo: 'L85', descripcion: 'Otras queratosis', categoria: 'Piel' },
  { codigo: 'L89', descripcion: 'Úlcera por presión (escaras)', categoria: 'Piel' },
  { codigo: 'L90', descripcion: 'Atrofia de piel', categoria: 'Piel' },
  { codigo: 'L91', descripcion: 'Hipertrofia de piel', categoria: 'Piel' },
  { codigo: 'L92', descripcion: 'Granuloma', categoria: 'Piel' },
  { codigo: 'L93', descripcion: 'Lupus cutáneo', categoria: 'Piel' },
  { codigo: 'L97', descripcion: 'Úlcera de pierna', categoria: 'Piel' },
  { codigo: 'L98', descripcion: 'Otros trastornos piel', categoria: 'Piel' },

  // M - Osteomusculares
  { codigo: 'M00', descripcion: 'Artritis séptica', categoria: 'Osteomuscular' },
  { codigo: 'M05', descripcion: 'Artritis reumatoide', categoria: 'Osteomuscular' },
  { codigo: 'M06', descripcion: 'Otras artritis reumatoides', categoria: 'Osteomuscular' },
  { codigo: 'M07', descripcion: 'Artritis psoriásica', categoria: 'Osteomuscular' },
  { codigo: 'M08', descripcion: 'Artritis juvenil', categoria: 'Osteomuscular' },
  { codigo: 'M10', descripcion: 'Gota', categoria: 'Osteomuscular' },
  { codigo: 'M13', descripcion: 'Artritis no especificada', categoria: 'Osteomuscular' },
  { codigo: 'M15', descripcion: 'Poliartrosis', categoria: 'Osteomuscular' },
  { codigo: 'M16', descripcion: 'Coxartrosis (cadera)', categoria: 'Osteomuscular' },
  { codigo: 'M17', descripcion: 'Gonartrosis (rodilla)', categoria: 'Osteomuscular' },
  { codigo: 'M19', descripcion: 'Otras artrosis', categoria: 'Osteomuscular' },
  { codigo: 'M23', descripcion: 'Lesión meniscal', categoria: 'Osteomuscular' },
  { codigo: 'M24', descripcion: 'Otros trastornos articulares', categoria: 'Osteomuscular' },
  { codigo: 'M25', descripcion: 'Dolor articular', categoria: 'Osteomuscular' },
  { codigo: 'M32', descripcion: 'Lupus eritematoso sistémico', categoria: 'Osteomuscular' },
  { codigo: 'M33', descripcion: 'Dermatomiositis', categoria: 'Osteomuscular' },
  { codigo: 'M34', descripcion: 'Esclerodermia', categoria: 'Osteomuscular' },
  { codigo: 'M35', descripcion: 'Enfermedad tejido conectivo', categoria: 'Osteomuscular' },
  { codigo: 'M40', descripcion: 'Cifosis (joroba)', categoria: 'Columna' },
  { codigo: 'M41', descripcion: 'Escoliosis', categoria: 'Columna' },
  { codigo: 'M43', descripcion: 'Otras deformidades columna', categoria: 'Columna' },
  { codigo: 'M45', descripcion: 'Espondilitis anquilosante', categoria: 'Columna' },
  { codigo: 'M47', descripcion: 'Espondilosis (artrosis columna)', categoria: 'Columna' },
  { codigo: 'M50', descripcion: 'Hernia disco cervical', categoria: 'Columna' },
  { codigo: 'M51', descripcion: 'Hernia disco lumbar', categoria: 'Columna' },
  { codigo: 'M53', descripcion: 'Otras dorsopatías', categoria: 'Columna' },
  { codigo: 'M54', descripcion: 'Lumbago / ciática / dorsalgia', categoria: 'Columna' },
  { codigo: 'M60', descripcion: 'Miositis', categoria: 'Osteomuscular' },
  { codigo: 'M62', descripcion: 'Otras trastornos musculares', categoria: 'Osteomuscular' },
  { codigo: 'M65', descripcion: 'Sinovitis / tenosinovitis', categoria: 'Osteomuscular' },
  { codigo: 'M67', descripcion: 'Ganglión / quiste sinovial', categoria: 'Osteomuscular' },
  { codigo: 'M70', descripcion: 'Bursitis por uso excesivo', categoria: 'Osteomuscular' },
  { codigo: 'M71', descripcion: 'Otras bursitis', categoria: 'Osteomuscular' },
  { codigo: 'M72', descripcion: 'Fascitis plantar', categoria: 'Osteomuscular' },
  { codigo: 'M75', descripcion: 'Lesiones del hombro', categoria: 'Osteomuscular' },
  { codigo: 'M76', descripcion: 'Tendinitis miembro inferior', categoria: 'Osteomuscular' },
  { codigo: 'M77', descripcion: 'Tendinitis otras', categoria: 'Osteomuscular' },
  { codigo: 'M79', descripcion: 'Reumatismo de partes blandas', categoria: 'Osteomuscular' },
  { codigo: 'M80', descripcion: 'Osteoporosis con fractura', categoria: 'Osteomuscular' },
  { codigo: 'M81', descripcion: 'Osteoporosis sin fractura', categoria: 'Osteomuscular' },
  { codigo: 'M84', descripcion: 'Fractura patológica', categoria: 'Osteomuscular' },
  { codigo: 'M86', descripcion: 'Osteomielitis', categoria: 'Osteomuscular' },

  // N - Genitourinarias
  { codigo: 'N00', descripcion: 'Síndrome nefrítico agudo', categoria: 'Nefrología' },
  { codigo: 'N03', descripcion: 'Nefritis crónica', categoria: 'Nefrología' },
  { codigo: 'N04', descripcion: 'Síndrome nefrótico', categoria: 'Nefrología' },
  { codigo: 'N10', descripcion: 'Nefritis aguda', categoria: 'Nefrología' },
  { codigo: 'N11', descripcion: 'Nefritis crónica', categoria: 'Nefrología' },
  { codigo: 'N13', descripcion: 'Uropatía obstructiva', categoria: 'Nefrología' },
  { codigo: 'N17', descripcion: 'Insuficiencia renal aguda', categoria: 'Nefrología' },
  { codigo: 'N18', descripcion: 'Insuficiencia renal crónica', categoria: 'Nefrología' },
  { codigo: 'N19', descripcion: 'Insuficiencia renal no especificada', categoria: 'Nefrología' },
  { codigo: 'N20', descripcion: 'Cálculo renal', categoria: 'Nefrología' },
  { codigo: 'N23', descripcion: 'Cólico renal', categoria: 'Nefrología' },
  { codigo: 'N28', descripcion: 'Otros trastornos renales', categoria: 'Nefrología' },
  { codigo: 'N30', descripcion: 'Cistitis', categoria: 'Urología' },
  { codigo: 'N31', descripcion: 'Vejiga neurógena', categoria: 'Urología' },
  { codigo: 'N32', descripcion: 'Otros trastornos vejiga', categoria: 'Urología' },
  { codigo: 'N34', descripcion: 'Uretritis', categoria: 'Urología' },
  { codigo: 'N35', descripcion: 'Estenosis uretral', categoria: 'Urología' },
  { codigo: 'N39', descripcion: 'Infección urinaria (ITU)', categoria: 'Urología' },
  { codigo: 'N40', descripcion: 'HPB (próstata agrandada)', categoria: 'Urología' },
  { codigo: 'N41', descripcion: 'Prostatitis', categoria: 'Urología' },
  { codigo: 'N43', descripcion: 'Hidrocele', categoria: 'Urología' },
  { codigo: 'N45', descripcion: 'Orquitis / epididimitis', categoria: 'Urología' },
  { codigo: 'N46', descripcion: 'Infertilidad masculina', categoria: 'Urología' },
  { codigo: 'N47', descripcion: 'Fimosis', categoria: 'Urología' },
  { codigo: 'N60', descripcion: 'Displasia mamaria benigna', categoria: 'Ginecología' },
  { codigo: 'N61', descripcion: 'Mastitis', categoria: 'Ginecología' },
  { codigo: 'N63', descripcion: 'Nódulo mamario', categoria: 'Ginecología' },
  { codigo: 'N64', descripcion: 'Otros trastornos de mama', categoria: 'Ginecología' },
  { codigo: 'N70', descripcion: 'Salpingitis / ooforitis', categoria: 'Ginecología' },
  { codigo: 'N71', descripcion: 'EPI (enfermedad pélvica)', categoria: 'Ginecología' },
  { codigo: 'N72', descripcion: 'Cervicitis', categoria: 'Ginecología' },
  { codigo: 'N75', descripcion: 'Quiste de Bartolino', categoria: 'Ginecología' },
  { codigo: 'N76', descripcion: 'Vaginitis', categoria: 'Ginecología' },
  { codigo: 'N80', descripcion: 'Endometriosis', categoria: 'Ginecología' },
  { codigo: 'N81', descripcion: 'Prolapso genital', categoria: 'Ginecología' },
  { codigo: 'N83', descripcion: 'Quiste ovárico', categoria: 'Ginecología' },
  { codigo: 'N85', descripcion: 'Pólipo endometrial', categoria: 'Ginecología' },
  { codigo: 'N86', descripcion: 'Erosión cervical', categoria: 'Ginecología' },
  { codigo: 'N87', descripcion: 'Displasia cervical (NIC)', categoria: 'Ginecología' },
  { codigo: 'N91', descripcion: 'Amenorrea', categoria: 'Ginecología' },
  { codigo: 'N92', descripcion: 'Menstruación abundante', categoria: 'Ginecología' },
  { codigo: 'N93', descripcion: 'Hemorragia uterina anormal', categoria: 'Ginecología' },
  { codigo: 'N94', descripcion: 'Dismenorrea / dolor pélvico', categoria: 'Ginecología' },
  { codigo: 'N95', descripcion: 'Menopausia / climaterio', categoria: 'Ginecología' },
  { codigo: 'N97', descripcion: 'Infertilidad femenina', categoria: 'Ginecología' },
  { codigo: 'N99', descripcion: 'Trastornos genitourinarios post-procedimiento', categoria: 'Urología' },

  // O - Embarazo (básicos)
  { codigo: 'O00', descripcion: 'Embarazo ectópico', categoria: 'Obstetricia' },
  { codigo: 'O03', descripcion: 'Aborto espontáneo', categoria: 'Obstetricia' },
  { codigo: 'O10', descripcion: 'HTA preexistente en embarazo', categoria: 'Obstetricia' },
  { codigo: 'O13', descripcion: 'Hipertensión gestacional', categoria: 'Obstetricia' },
  { codigo: 'O14', descripcion: 'Preeclampsia', categoria: 'Obstetricia' },
  { codigo: 'O15', descripcion: 'Eclampsia', categoria: 'Obstetricia' },
  { codigo: 'O20', descripcion: 'Hemorragia precoz embarazo', categoria: 'Obstetricia' },
  { codigo: 'O21', descripcion: 'Hiperemesis gravídica', categoria: 'Obstetricia' },
  { codigo: 'O23', descripcion: 'ITU en embarazo', categoria: 'Obstetricia' },
  { codigo: 'O24', descripcion: 'Diabetes gestacional', categoria: 'Obstetricia' },
  { codigo: 'O26', descripcion: 'Cuidados maternos varios', categoria: 'Obstetricia' },
  { codigo: 'O30', descripcion: 'Embarazo múltiple', categoria: 'Obstetricia' },
  { codigo: 'O34', descripcion: 'Anomalías pélvicas', categoria: 'Obstetricia' },
  { codigo: 'O36', descripcion: 'Problemas fetales', categoria: 'Obstetricia' },
  { codigo: 'O42', descripcion: 'RPM (ruptura membranas)', categoria: 'Obstetricia' },
  { codigo: 'O44', descripcion: 'Placenta previa', categoria: 'Obstetricia' },
  { codigo: 'O45', descripcion: 'DPP (desprendimiento placenta)', categoria: 'Obstetricia' },
  { codigo: 'O48', descripcion: 'Embarazo prolongado', categoria: 'Obstetricia' },
  { codigo: 'O60', descripcion: 'Parto prematuro', categoria: 'Obstetricia' },
  { codigo: 'O70', descripcion: 'Desgarro perineal parto', categoria: 'Obstetricia' },
  { codigo: 'O80', descripcion: 'Parto único espontáneo', categoria: 'Obstetricia' },
  { codigo: 'O82', descripcion: 'Parto por cesárea', categoria: 'Obstetricia' },
  { codigo: 'O90', descripcion: 'Complicaciones puerperio', categoria: 'Obstetricia' },
  { codigo: 'O99', descripcion: 'Otras enfermedades maternas', categoria: 'Obstetricia' },

  // R - Síntomas
  { codigo: 'R05', descripcion: 'Tos', categoria: 'Síntomas' },
  { codigo: 'R06', descripcion: 'Disnea / dificultad respiratoria', categoria: 'Síntomas' },
  { codigo: 'R07', descripcion: 'Dolor de garganta / pecho', categoria: 'Síntomas' },
  { codigo: 'R10', descripcion: 'Dolor abdominal', categoria: 'Síntomas' },
  { codigo: 'R11', descripcion: 'Náuseas / vómitos', categoria: 'Síntomas' },
  { codigo: 'R12', descripcion: 'Acidez / pirosis', categoria: 'Síntomas' },
  { codigo: 'R13', descripcion: 'Disfagia', categoria: 'Síntomas' },
  { codigo: 'R14', descripcion: 'Flatulencia / meteorismo', categoria: 'Síntomas' },
  { codigo: 'R15', descripcion: 'Incontinencia fecal', categoria: 'Síntomas' },
  { codigo: 'R16', descripcion: 'Hepatomegalia', categoria: 'Síntomas' },
  { codigo: 'R17', descripcion: 'Ictericia', categoria: 'Síntomas' },
  { codigo: 'R18', descripcion: 'Ascitis', categoria: 'Síntomas' },
  { codigo: 'R19', descripcion: 'Otros síntomas digestivos', categoria: 'Síntomas' },
  { codigo: 'R20', descripcion: 'Alteraciones sensibilidad', categoria: 'Síntomas' },
  { codigo: 'R21', descripcion: 'Erupción cutánea', categoria: 'Síntomas' },
  { codigo: 'R22', descripcion: 'Tumoración / masa', categoria: 'Síntomas' },
  { codigo: 'R23', descripcion: 'Cianosis / palidez', categoria: 'Síntomas' },
  { codigo: 'R25', descripcion: 'Movimientos involuntarios', categoria: 'Síntomas' },
  { codigo: 'R26', descripcion: 'Trastornos de la marcha', categoria: 'Síntomas' },
  { codigo: 'R27', descripcion: 'Falta de coordinación', categoria: 'Síntomas' },
  { codigo: 'R29', descripcion: 'Otros síntomas neurológicos', categoria: 'Síntomas' },
  { codigo: 'R30', descripcion: 'Dolor al orinar', categoria: 'Síntomas' },
  { codigo: 'R31', descripcion: 'Hematuria (sangre en orina)', categoria: 'Síntomas' },
  { codigo: 'R32', descripcion: 'Incontinencia urinaria', categoria: 'Síntomas' },
  { codigo: 'R33', descripcion: 'Retención urinaria', categoria: 'Síntomas' },
  { codigo: 'R34', descripcion: 'Anuria / oliguria', categoria: 'Síntomas' },
  { codigo: 'R35', descripcion: 'Poliuria', categoria: 'Síntomas' },
  { codigo: 'R39', descripcion: 'Otros síntomas urinarios', categoria: 'Síntomas' },
  { codigo: 'R40', descripcion: 'Somnolencia / coma', categoria: 'Síntomas' },
  { codigo: 'R41', descripcion: 'Alteraciones cognitivas', categoria: 'Síntomas' },
  { codigo: 'R42', descripcion: 'Mareo / vértigo', categoria: 'Síntomas' },
  { codigo: 'R43', descripcion: 'Alteraciones olfato/gusto', categoria: 'Síntomas' },
  { codigo: 'R44', descripcion: 'Alucinaciones', categoria: 'Síntomas' },
  { codigo: 'R45', descripcion: 'Ansiedad / agitación', categoria: 'Síntomas' },
  { codigo: 'R46', descripcion: 'Comportamiento anormal', categoria: 'Síntomas' },
  { codigo: 'R47', descripcion: 'Trastornos del habla', categoria: 'Síntomas' },
  { codigo: 'R48', descripcion: 'Trastornos aprendizaje', categoria: 'Síntomas' },
  { codigo: 'R49', descripcion: 'Trastornos de la voz', categoria: 'Síntomas' },
  { codigo: 'R50', descripcion: 'Fiebre', categoria: 'Síntomas' },
  { codigo: 'R51', descripcion: 'Cefalea (dolor de cabeza)', categoria: 'Síntomas' },
  { codigo: 'R52', descripcion: 'Dolor crónico / agudo', categoria: 'Síntomas' },
  { codigo: 'R53', descripcion: 'Fatiga / astenia', categoria: 'Síntomas' },
  { codigo: 'R54', descripcion: 'Senilidad', categoria: 'Síntomas' },
  { codigo: 'R55', descripcion: 'Síncope (desmayo)', categoria: 'Síntomas' },
  { codigo: 'R56', descripcion: 'Convulsiones', categoria: 'Síntomas' },
  { codigo: 'R57', descripcion: 'Shock', categoria: 'Síntomas' },
  { codigo: 'R58', descripcion: 'Hemorragia', categoria: 'Síntomas' },
  { codigo: 'R59', descripcion: 'Adenomegalia (ganglios inflamados)', categoria: 'Síntomas' },
  { codigo: 'R60', descripcion: 'Edema', categoria: 'Síntomas' },
  { codigo: 'R61', descripcion: 'Sudoración excesiva', categoria: 'Síntomas' },
  { codigo: 'R62', descripcion: 'Retraso del desarrollo', categoria: 'Síntomas' },
  { codigo: 'R63', descripcion: 'Trastornos alimentarios', categoria: 'Síntomas' },
  { codigo: 'R64', descripcion: 'Caquexia (pérdida peso)', categoria: 'Síntomas' },
  { codigo: 'R68', descripcion: 'Otros síntomas generales', categoria: 'Síntomas' },
  { codigo: 'R69', descripcion: 'Enfermedad no especificada', categoria: 'Síntomas' },
  { codigo: 'R70', descripcion: 'VSG elevada', categoria: 'Hallazgos' },
  { codigo: 'R71', descripcion: 'Anomalías glóbulos rojos', categoria: 'Hallazgos' },
  { codigo: 'R72', descripcion: 'Anomalías glóbulos blancos', categoria: 'Hallazgos' },
  { codigo: 'R73', descripcion: 'Glucosa elevada en sangre', categoria: 'Hallazgos' },
  { codigo: 'R74', descripcion: 'Enzimas hepáticas elevadas', categoria: 'Hallazgos' },
  { codigo: 'R75', descripcion: 'Hallazgo serológico VIH', categoria: 'Hallazgos' },
  { codigo: 'R76', descripcion: 'Otros hallazgos serológicos', categoria: 'Hallazgos' },
  { codigo: 'R77', descripcion: 'Anomalías proteínas plasmáticas', categoria: 'Hallazgos' },
  { codigo: 'R78', descripcion: 'Drogas en sangre', categoria: 'Hallazgos' },
  { codigo: 'R79', descripcion: 'Otros hallazgos sanguíneos', categoria: 'Hallazgos' },
  { codigo: 'R80', descripcion: 'Proteinuria aislada', categoria: 'Hallazgos' },
  { codigo: 'R81', descripcion: 'Glucosuria', categoria: 'Hallazgos' },
  { codigo: 'R82', descripcion: 'Otros hallazgos urinarios', categoria: 'Hallazgos' },
  { codigo: 'R83', descripcion: 'Hallazgos LCR', categoria: 'Hallazgos' },
  { codigo: 'R89', descripcion: 'Hallazgos otros órganos', categoria: 'Hallazgos' },
  { codigo: 'R90', descripcion: 'Hallazgos SNC estudios', categoria: 'Hallazgos' },
  { codigo: 'R91', descripcion: 'Nódulo pulmonar (Rx)', categoria: 'Hallazgos' },
  { codigo: 'R92', descripcion: 'Hallazgos mamarios (imagen)', categoria: 'Hallazgos' },
  { codigo: 'R93', descripcion: 'Hallazgos imagen digestivos', categoria: 'Hallazgos' },
  { codigo: 'R94', descripcion: 'Hallazgos funcionales', categoria: 'Hallazgos' },
  { codigo: 'R95', descripcion: 'Muerte súbita infantil', categoria: 'Otras' },
  { codigo: 'R96', descripcion: 'Muerte súbita otra', categoria: 'Otras' },
  { codigo: 'R99', descripcion: 'Causa desconocida de muerte', categoria: 'Otras' },

  // Z - Factores que influyen en salud
  { codigo: 'Z00', descripcion: 'Control general de salud', categoria: 'Preventivos' },
  { codigo: 'Z01', descripcion: 'Examen periódico', categoria: 'Preventivos' },
  { codigo: 'Z02', descripcion: 'Examen por trabajo/seguro', categoria: 'Preventivos' },
  { codigo: 'Z03', descripcion: 'Observación por sospecha', categoria: 'Preventivos' },
  { codigo: 'Z04', descripcion: 'Examen por otras causas', categoria: 'Preventivos' },
  { codigo: 'Z08', descripcion: 'Control post-tratamiento neoplasia', categoria: 'Preventivos' },
  { codigo: 'Z09', descripcion: 'Control post-tratamiento otras', categoria: 'Preventivos' },
  { codigo: 'Z10', descripcion: 'Chequeo poblacional', categoria: 'Preventivos' },
  { codigo: 'Z11', descripcion: 'Screening enfermedades infecciosas', categoria: 'Preventivos' },
  { codigo: 'Z12', descripcion: 'Screening neoplasias', categoria: 'Preventivos' },
  { codigo: 'Z13', descripcion: 'Screening otras enfermedades', categoria: 'Preventivos' },
  { codigo: 'Z20', descripcion: 'Contacto con enfermedades infecciosas', categoria: 'Preventivos' },
  { codigo: 'Z21', descripcion: 'VIH asintomático', categoria: 'Preventivos' },
  { codigo: 'Z22', descripcion: 'Portador de enfermedad', categoria: 'Preventivos' },
  { codigo: 'Z23', descripcion: 'Vacunación bacteriana', categoria: 'Preventivos' },
  { codigo: 'Z24', descripcion: 'Vacunación viral', categoria: 'Preventivos' },
  { codigo: 'Z25', descripcion: 'Vacunación otras virales', categoria: 'Preventivos' },
  { codigo: 'Z26', descripcion: 'Vacunación otras', categoria: 'Preventivos' },
  { codigo: 'Z27', descripcion: 'Vacunación combinada', categoria: 'Preventivos' },
  { codigo: 'Z28', descripcion: 'Vacunación no realizada', categoria: 'Preventivos' },
  { codigo: 'Z29', descripcion: 'Otras medidas profilácticas', categoria: 'Preventivos' },
  { codigo: 'Z30', descripcion: 'Anticoncepción', categoria: 'Preventivos' },
  { codigo: 'Z31', descripcion: 'Fertilidad', categoria: 'Preventivos' },
  { codigo: 'Z32', descripcion: 'Test de embarazo', categoria: 'Preventivos' },
  { codigo: 'Z33', descripcion: 'Embarazo incidental', categoria: 'Preventivos' },
  { codigo: 'Z34', descripcion: 'Control embarazo normal', categoria: 'Preventivos' },
  { codigo: 'Z35', descripcion: 'Control embarazo de alto riesgo', categoria: 'Preventivos' },
  { codigo: 'Z36', descripcion: 'Screening prenatal', categoria: 'Preventivos' },
  { codigo: 'Z37', descripcion: 'Resultado del parto', categoria: 'Preventivos' },
  { codigo: 'Z38', descripcion: 'Recién nacido vivo', categoria: 'Preventivos' },
  { codigo: 'Z39', descripcion: 'Control postparto', categoria: 'Preventivos' },
  { codigo: 'Z40', descripcion: 'Cirugía profiláctica', categoria: 'Preventivos' },
  { codigo: 'Z41', descripcion: 'Procedimientos no terapéuticos', categoria: 'Preventivos' },
  { codigo: 'Z42', descripcion: 'Cuidados post-cirugía reconstructiva', categoria: 'Preventivos' },
  { codigo: 'Z43', descripcion: 'Mantenimiento de ostomías', categoria: 'Preventivos' },
  { codigo: 'Z44', descripcion: 'Colocación prótesis', categoria: 'Preventivos' },
  { codigo: 'Z45', descripcion: 'Ajuste de dispositivos', categoria: 'Preventivos' },
  { codigo: 'Z46', descripcion: 'Colocación otros dispositivos', categoria: 'Preventivos' },
  { codigo: 'Z47', descripcion: 'Cuidados post-ortopédicos', categoria: 'Preventivos' },
  { codigo: 'Z48', descripcion: 'Cuidados post-cirugía otros', categoria: 'Preventivos' },
  { codigo: 'Z50', descripcion: 'Rehabilitación', categoria: 'Preventivos' },
  { codigo: 'Z51', descripcion: 'Otros cuidados médicos', categoria: 'Preventivos' },
  { codigo: 'Z52', descripcion: 'Donante de órganos', categoria: 'Preventivos' },
  { codigo: 'Z53', descripcion: 'Procedimiento no realizado', categoria: 'Preventivos' },
  { codigo: 'Z54', descripcion: 'Convalecencia', categoria: 'Preventivos' },
  { codigo: 'Z55', descripcion: 'Problemas educativos', categoria: 'Sociales' },
  { codigo: 'Z56', descripcion: 'Problemas laborales', categoria: 'Sociales' },
  { codigo: 'Z57', descripcion: 'Riesgo laboral', categoria: 'Sociales' },
  { codigo: 'Z58', descripcion: 'Problemas ambientales', categoria: 'Sociales' },
  { codigo: 'Z59', descripcion: 'Problemas vivienda/económicos', categoria: 'Sociales' },
  { codigo: 'Z60', descripcion: 'Problemas sociales', categoria: 'Sociales' },
  { codigo: 'Z61', descripcion: 'Problemas infancia', categoria: 'Sociales' },
  { codigo: 'Z62', descripcion: 'Problemas crianza', categoria: 'Sociales' },
  { codigo: 'Z63', descripcion: 'Problemas familiares', categoria: 'Sociales' },
  { codigo: 'Z64', descripcion: 'Problemas conducta', categoria: 'Sociales' },
  { codigo: 'Z65', descripcion: 'Problemas psicosociales', categoria: 'Sociales' },
  { codigo: 'Z70', descripcion: 'Consejería sexual', categoria: 'Preventivos' },
  { codigo: 'Z71', descripcion: 'Consejería otras', categoria: 'Preventivos' },
  { codigo: 'Z72', descripcion: 'Problemas estilo de vida', categoria: 'Sociales' },
  { codigo: 'Z73', descripcion: 'Problemas manejo vida', categoria: 'Sociales' },
  { codigo: 'Z74', descripcion: 'Dependencia cuidado', categoria: 'Sociales' },
  { codigo: 'Z75', descripcion: 'Problemas servicios salud', categoria: 'Sociales' },
  { codigo: 'Z76', descripcion: 'Contacto servicios salud', categoria: 'Preventivos' },
  { codigo: 'Z80', descripcion: 'Antecedentes familiares neoplasias', categoria: 'Antecedentes' },
  { codigo: 'Z81', descripcion: 'Antecedentes familiares mentales', categoria: 'Antecedentes' },
  { codigo: 'Z82', descripcion: 'Antecedentes familiares otras', categoria: 'Antecedentes' },
  { codigo: 'Z83', descripcion: 'Antecedentes familiares otras', categoria: 'Antecedentes' },
  { codigo: 'Z85', descripcion: 'Antecedentes personales neoplasia', categoria: 'Antecedentes' },
  { codigo: 'Z86', descripcion: 'Antecedentes personales otras', categoria: 'Antecedentes' },
  { codigo: 'Z87', descripcion: 'Antecedentes personales otras', categoria: 'Antecedentes' },
  { codigo: 'Z88', descripcion: 'Alergia a medicamentos', categoria: 'Antecedentes' },
  { codigo: 'Z89', descripcion: 'Ausencia adquirida de miembros', categoria: 'Antecedentes' },
  { codigo: 'Z90', descripcion: 'Ausencia adquirida de órganos', categoria: 'Antecedentes' },
  { codigo: 'Z91', descripcion: 'Factores de riesgo personales', categoria: 'Antecedentes' },
  { codigo: 'Z92', descripcion: 'Antecedentes tratamiento', categoria: 'Antecedentes' },
  { codigo: 'Z93', descripcion: 'Ostomía', categoria: 'Antecedentes' },
  { codigo: 'Z94', descripcion: 'Trasplante de órganos', categoria: 'Antecedentes' },
  { codigo: 'Z95', descripcion: 'Implantes cardiovasculares', categoria: 'Antecedentes' },
  { codigo: 'Z96', descripcion: 'Otros implantes', categoria: 'Antecedentes' },
  { codigo: 'Z97', descripcion: 'Dispositivos externos', categoria: 'Antecedentes' },
  { codigo: 'Z98', descripcion: 'Otros estados post-cirugía', categoria: 'Antecedentes' },
  { codigo: 'Z99', descripcion: 'Dependencia de dispositivos', categoria: 'Antecedentes' },
];

// ─── Helper: buscar códigos ─────────────────────────────────

export function buscarCie10(termino: string): Cie10Entry[] {
  const q = termino.toLowerCase().trim();
  if (!q) return [];
  return CIE10_DATA.filter(
    (e) =>
      e.codigo.toLowerCase().startsWith(q) ||
      e.descripcion.toLowerCase().includes(q),
  ).slice(0, 20);
}
